import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, AlarmClock, AudioLines, Download, Gauge, Image, ListMusic, Palette, Save, ScanLine, Sparkles, TimerReset, Upload, Video, Wand2, X } from 'lucide-react'
import { api } from './api'
import { translator } from './i18n'

const sleepPresets=[15,30,45,60,90]
const keyNames=['C','C#/Db','D','D#/Eb','E','F','F#/Gb','G','G#/Ab','A','A#/Bb','B']

function currentSongId(){
  const audio=[...document.querySelectorAll('audio')].find(a=>a.src?.includes('/media/')&&!a.paused)||[...document.querySelectorAll('audio')].find(a=>a.src?.includes('/media/'))
  const m=audio?.src?.match(/\/media\/(\d+)/);return m?Number(m[1]):null
}
function activeAudio(){return [...document.querySelectorAll('audio')].find(a=>a.src?.includes('/media/')&&!a.paused)||[...document.querySelectorAll('audio')].find(a=>a.src?.includes('/media/'))||null}
function dispatchKey(code,ctrlKey=false){window.dispatchEvent(new KeyboardEvent('keydown',{code,ctrlKey,bubbles:true}))}
function fmtLeft(ms){if(ms<=0)return '0:00';const s=Math.ceil(ms/1000),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}`}
function goertzel(samples,sampleRate,frequency){const w=2*Math.PI*frequency/sampleRate,coeff=2*Math.cos(w);let q0=0,q1=0,q2=0;for(let i=0;i<samples.length;i++){q0=coeff*q1-q2+samples[i];q2=q1;q1=q0}return q1*q1+q2*q2-coeff*q1*q2}
function percentile(values,p){if(!values.length)return 0;const s=[...values].sort((a,b)=>a-b);return s[Math.min(s.length-1,Math.max(0,Math.floor((s.length-1)*p)))]}
function analyzeBuffer(buffer){
  const source=buffer.getChannelData(0),sr=buffer.sampleRate,maxSamples=Math.min(source.length,Math.floor(sr*120)),frame=Math.max(512,Math.floor(sr*.02));let sum=0,peak=0,zc=0,last=source[0]||0;const env=[]
  for(let i=0;i<maxSamples;i++){const v=source[i];sum+=v*v;peak=Math.max(peak,Math.abs(v));if((v>=0)!=(last>=0))zc++;last=v}
  for(let i=0;i<maxSamples-frame;i+=frame){let e=0;for(let j=0;j<frame;j++){const v=source[i+j];e+=v*v}env.push(Math.sqrt(e/frame))}
  const rms=Math.sqrt(sum/Math.max(1,maxSamples)),lo=percentile(env,.1),hi=percentile(env,.9),dynamicRange=20*Math.log10((hi+1e-6)/(lo+1e-6)),zcr=zc/(maxSamples/Math.max(1,sr))
  const onset=env.map((v,i)=>Math.max(0,v-(env[i-1]||v)));const fps=sr/frame;let bestBpm=0,bestScore=-1
  for(let bpm=60;bpm<=190;bpm++){const lag=Math.max(1,Math.round(fps*60/bpm));let score=0;for(let i=lag;i<onset.length;i++)score+=onset[i]*onset[i-lag];if(score>bestScore){bestScore=score;bestBpm=bpm}}
  const analysisSeconds=Math.min(24,buffer.duration),windowSize=4096,windows=12,energies=new Array(12).fill(0)
  for(let w=0;w<windows;w++){const start=Math.floor(Math.max(0,analysisSeconds*sr-windowSize)*w/Math.max(1,windows-1));const chunk=new Float32Array(windowSize);for(let i=0;i<windowSize;i++)chunk[i]=source[Math.max(0,Math.min(source.length-1,start+i))]||0;for(let pc=0;pc<12;pc++){let e=0;for(let octave=3;octave<=5;octave++){const midi=12*(octave+1)+pc,f=440*Math.pow(2,(midi-69)/12);e+=goertzel(chunk,sr,f)}energies[pc]+=e}}
  const keyIndex=energies.indexOf(Math.max(...energies)),brightness=Math.min(1,zcr/8000),energy=Math.min(1,rms/.32),danceability=Math.min(1,Math.max(0,(bestBpm-60)/100)*.55+Math.min(1,bestScore*800)*.25+(1-Math.min(1,dynamicRange/35))*.2),mood=energy>.62&&bestBpm>118?'energetic':energy<.23?'calm':brightness>.52?'bright':dynamicRange>18?'dynamic':'balanced'
  return {bpm:bestBpm,key:keyNames[keyIndex]||'',mood,energy:Number(energy.toFixed(3)),danceability:Number(danceability.toFixed(3)),dynamicRange:Number(dynamicRange.toFixed(2)),rms:Number(rms.toFixed(5)),peak:Number(peak.toFixed(5)),brightness:Number(brightness.toFixed(3)),duration:Number(buffer.duration.toFixed(2))}
}

export default function FeatureHub(){
  const [open,setOpen]=useState(false),[tab,setTab]=useState('tools'),[settings,setSettings]=useState({}),[library,setLibrary]=useState([]),[playlists,setPlaylists]=useState([]),[songId,setSongId]=useState(null),[profile,setProfile]=useState(null),[analysis,setAnalysis]=useState(null),[busy,setBusy]=useState(''),[toast,setToast]=useState(''),[sleepEnd,setSleepEnd]=useState(0),[now,setNow]=useState(Date.now()),[wallpaper,setWallpaper]=useState(''),[canvas,setCanvas]=useState('')
  const [t,lang]=translator(settings.language);const timerRef=useRef(null),sleepLabel=lang==='fa'?'تایمر خواب':'Sleep timer'
  const current=useMemo(()=>library.find(s=>s.id===songId)||null,[library,songId])
  const ping=(m)=>{setToast(m);clearTimeout(window.__neoPlusToast);window.__neoPlusToast=setTimeout(()=>setToast(''),2400)}
  const refresh=async()=>{const [s,lib,pls]=await Promise.all([api.settings(),api.library(),api.playlists(true)]);setSettings(s);setLibrary(lib);setPlaylists(pls)}
  useEffect(()=>{refresh().catch(()=>{})},[])
  useEffect(()=>{const id=setInterval(()=>{setSongId(currentSongId());setNow(Date.now())},500);return()=>clearInterval(id)},[])
  useEffect(()=>{if(!songId){setProfile(null);setWallpaper('');setCanvas('');return}api.profile(songId).then(async p=>{setProfile(p);try{setWallpaper(await window.pywebview?.api?.track_asset_data?.(songId,'wallpaper')||'')}catch{};try{setCanvas(await window.pywebview?.api?.track_asset_data?.(songId,'canvas')||'')}catch{}}).catch(()=>{})},[songId])
  useEffect(()=>{if(!sleepEnd)return;clearInterval(timerRef.current);timerRef.current=setInterval(()=>{const remain=sleepEnd-Date.now();setNow(Date.now());if(remain<=0){document.querySelectorAll('audio').forEach(a=>a.pause());setSleepEnd(0);clearInterval(timerRef.current);ping(lang==='fa'?'تایمر خواب تمام شد':'Sleep timer finished')}},500);return()=>clearInterval(timerRef.current)},[sleepEnd,lang])
  useEffect(()=>{if(!('mediaSession'in navigator))return;try{if(current)navigator.mediaSession.metadata=new MediaMetadata({title:current.title,artist:current.artist||'NEO Player',album:current.album||'',artwork:[{src:new URL(`/cover/${current.id}`,location.href).href,sizes:'512x512'}]});navigator.mediaSession.playbackState=activeAudio()?.paused?'paused':'playing'}catch{};const handlers={play:()=>activeAudio()?.play(),pause:()=>activeAudio()?.pause(),nexttrack:()=>dispatchKey('ArrowRight',true),previoustrack:()=>dispatchKey('ArrowLeft',true),seekto:d=>{const a=activeAudio();if(a&&Number.isFinite(d.seekTime))a.currentTime=d.seekTime}};Object.entries(handlers).forEach(([k,v])=>{try{navigator.mediaSession.setActionHandler(k,v)}catch{}})},[current?.id,now])
  useEffect(()=>{const fix=()=>{const select=document.querySelector('.player-tools select');if(select){const vals=['0.75','1','1.25','1.5','2'];[...select.options].forEach((o,i)=>{if(vals[i])o.value=vals[i]})}};fix();const mo=new MutationObserver(fix);mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()},[])

  const setSleep=(minutes)=>{if(!minutes){setSleepEnd(0);clearInterval(timerRef.current);return}setSleepEnd(Date.now()+minutes*60000);ping(`${sleepLabel} · ${minutes}m`)}
  const importM3u8=async()=>{setBusy('m3u');try{const r=await window.pywebview?.api?.import_m3u8?.();if(r){await refresh();ping(`${t('importM3u8')} ✓`)}}catch(e){ping(String(e))}finally{setBusy('')}}
  const exportM3u8=async()=>{const id=Number(document.getElementById('neo-plus-playlist')?.value||0);if(!id)return;setBusy('m3u');try{const r=await window.pywebview?.api?.export_m3u8?.(id);if(r)ping(`${t('exportM3u8')} ✓`)}catch(e){ping(String(e))}finally{setBusy('')}}
  const exportBackup=async()=>{setBusy('backup');try{const p=await window.pywebview?.api?.export_full_backup?.();if(p)ping(`${t('exportBackup')} ✓`)}catch(e){ping(String(e))}finally{setBusy('')}}
  const restoreBackup=async()=>{setBusy('backup');try{const ok=await window.pywebview?.api?.restore_full_backup?.();if(ok){await refresh();ping(`${t('importBackup')} ✓`)}}catch(e){ping(String(e))}finally{setBusy('')}}
  const chooseAsset=async(kind)=>{if(!songId)return;setBusy(kind);try{const p=await window.pywebview?.api?.pick_track_asset?.(songId,kind);if(p){const next=await api.profile(songId);setProfile(next);if(kind==='artwork')document.querySelectorAll(`img[src*="/cover/${songId}"]`).forEach(img=>img.src=`/cover/${songId}?v=${Date.now()}`);const data=await window.pywebview?.api?.track_asset_data?.(songId,kind);if(kind==='wallpaper')setWallpaper(data||'');if(kind==='canvas')setCanvas(data||'');ping('Track+ ✓')}}catch(e){ping(String(e))}finally{setBusy('')}}
  const clearAssets=async()=>{if(!songId)return;await window.pywebview?.api?.clear_track_assets?.(songId);setProfile(await api.profile(songId));setWallpaper('');setCanvas('');ping(t('reset'))}
  const analyze=async()=>{if(!current)return;setBusy('analysis');try{const ctx=new (window.AudioContext||window.webkitAudioContext)(),res=await fetch(`/media/${current.id}`),array=await res.arrayBuffer(),buffer=await ctx.decodeAudioData(array.slice(0)),out=analyzeBuffer(buffer);setAnalysis(out);await window.pywebview?.api?.save_track_analysis?.(current.id,out);await refresh();ping((lang==='fa'?'تحلیل ترک کامل شد':'Track analysis complete')+` · ${out.bpm} BPM · ${out.key}`);ctx.close()}catch(e){ping(lang==='fa'?`تحلیل ناموفق: ${e}`:`Analysis failed: ${e}`)}finally{setBusy('')}}

  return <>
    {wallpaper&&<div className="neo-track-wallpaper" style={{backgroundImage:`url(${wallpaper})`,opacity:profile?.wallpaperOpacity??.28,filter:`blur(${profile?.wallpaperBlur??18}px)`}}/>}
    {canvas&&<video className="neo-track-canvas" key={canvas.slice(0,40)} src={canvas} autoPlay muted loop playsInline style={{opacity:profile?.wallpaperOpacity??.28}}/>}
    <button className="neo-plus-fab" onClick={()=>setOpen(!open)} title="NEO+"><Sparkles/><span>NEO+</span>{sleepEnd>Date.now()&&<em>{fmtLeft(sleepEnd-now)}</em>}</button>
    {open&&<div className="neo-plus-panel" dir={lang==='fa'?'rtl':'ltr'}><div className="neo-plus-head"><div><b>NEO+</b><small>{lang==='fa'?'ابزارهای پیشرفته آفلاین':'Advanced offline tools'}</small></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="neo-plus-tabs">{[['tools',Wand2],['track',AudioLines],['library',ListMusic],['offline',Save]].map(([id,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{id==='tools'?(lang==='fa'?'ابزارها':'Tools'):id==='track'?'Track+':id==='library'?t('library'):t('offline')}</button>)}</div>
      {tab==='tools'&&<div className="neo-plus-body"><section><h3><AlarmClock/>{sleepLabel}</h3><div className="preset-row">{sleepPresets.map(m=><button key={m} className={sleepEnd&&Math.abs((sleepEnd-Date.now())/60000-m)<1?'active':''} onClick={()=>setSleep(m)}>{m}m</button>)}<button onClick={()=>setSleep(0)}>{t('off')}</button></div>{sleepEnd>Date.now()&&<div className="countdown"><TimerReset/>{fmtLeft(sleepEnd-now)}</div>}</section><section><h3><Gauge/>{lang==='fa'?'تحلیل محلی ترک':'Local track analysis'}</h3>{current?<><div className="current-chip"><img src={`/cover/${current.id}`} onError={e=>e.currentTarget.style.display='none'}/><span><b>{current.title}</b><small>{current.artist||'—'}</small></span></div><button className="neo-plus-primary" disabled={busy==='analysis'} onClick={analyze}><ScanLine/>{busy==='analysis'?'…':lang==='fa'?'تحلیل BPM / Key / Energy':'Analyze BPM / Key / Energy'}</button>{analysis&&<div className="analysis-grid"><b>{analysis.bpm}<small>BPM</small></b><b>{analysis.key}<small>Key</small></b><b>{analysis.mood}<small>Mood</small></b><b>{Math.round(analysis.energy*100)}%<small>Energy</small></b><b>{analysis.dynamicRange}<small>DR dB</small></b><b>{Math.round(analysis.danceability*100)}%<small>Dance</small></b></div>}</>:<p className="neo-muted">{lang==='fa'?'یک ترک را پخش کن.':'Play a track first.'}</p>}</section></div>}
      {tab==='track'&&<div className="neo-plus-body"><section><h3><Palette/>Track+</h3>{current?<><div className="current-chip"><img src={`/cover/${current.id}?v=${profile?.artworkPath||''}`}/><span><b>{current.title}</b><small>{current.album||current.artist||'—'}</small></span></div><div className="asset-grid"><button onClick={()=>chooseAsset('artwork')}><Image/>{lang==='fa'?'کاور سفارشی':'Custom artwork'}</button><button onClick={()=>chooseAsset('wallpaper')}><Image/>{lang==='fa'?'پس‌زمینه':'Wallpaper'}</button><button onClick={()=>chooseAsset('canvas')}><Video/>{lang==='fa'?'ویدیوی Canvas':'Canvas video'}</button><button onClick={clearAssets}><X/>{t('reset')}</button></div><label className="neo-range">{lang==='fa'?'شفافیت پس‌زمینه':'Wallpaper opacity'}<input type="range" min="0" max=".85" step=".05" value={profile?.wallpaperOpacity??.28} onChange={async e=>{const v=Number(e.target.value);setProfile(p=>({...p,wallpaperOpacity:v}));await api.saveProfile(current.id,{wallpaperOpacity:v})}}/></label><label className="neo-range">{lang==='fa'?'محو شدگی':'Blur'}<input type="range" min="0" max="48" step="1" value={profile?.wallpaperBlur??18} onChange={async e=>{const v=Number(e.target.value);setProfile(p=>({...p,wallpaperBlur:v}));await api.saveProfile(current.id,{wallpaperBlur:v})}}/></label></>:<p className="neo-muted">{lang==='fa'?'ابتدا یک آهنگ پخش کن.':'Play a song first.'}</p>}</section></div>}
      {tab==='library'&&<div className="neo-plus-body"><section><h3><ListMusic/>M3U8</h3><div className="asset-grid"><button disabled={!!busy} onClick={importM3u8}><Upload/>{t('importM3u8')}</button><div className="export-box"><select id="neo-plus-playlist"><option value="">{t('playlists')}</option>{playlists.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!!busy} onClick={exportM3u8}><Download/>{t('exportM3u8')}</button></div></div></section><section><h3><Activity/>{lang==='fa'?'Media Session ویندوز':'Windows Media Session'}</h3><p className="neo-muted">{lang==='fa'?'Play/Pause، Previous، Next و Seek به Media Session مرورگر متصل شده‌اند.':'Play/Pause, Previous, Next and Seek are connected to the browser media session.'}</p></section></div>}
      {tab==='offline'&&<div className="neo-plus-body"><section><h3><Save/>{t('backup')}</h3><div className="asset-grid"><button disabled={!!busy} onClick={exportBackup}><Download/>{t('exportBackup')}</button><button disabled={!!busy} onClick={restoreBackup}><Upload/>{t('importBackup')}</button></div><p className="neo-muted">{lang==='fa'?'نسخه کامل شامل تنظیمات، پوشه‌ها، پلی‌لیست‌ها، متن‌ها، Track+، صف و وضعیت ترک‌هاست.':'Full backup includes settings, folders, playlists, lyrics, Track+, queue and track state.'}</p></section></div>}
    </div>}
    {toast&&<div className="neo-plus-toast">{toast}</div>}
  </>
}
