using NeoPlayer.Windows.Data;
using NeoPlayer.Windows.Models;
using System.Diagnostics;
using System.Text.Json;
namespace NeoPlayer.Windows.Services;
public sealed class AudioAnalysisService(NeoDatabase db)
{
 public event Action<int,int,string>? Progress;
 public async Task AnalyzeLibraryAsync(IEnumerable<Song> songs,CancellationToken ct=default){var list=songs.ToList();int i=0;foreach(var s in list){ct.ThrowIfCancellationRequested();Progress?.Invoke(i++,list.Count,s.Title);await AnalyzeAsync(s,ct);await Task.Yield();}Progress?.Invoke(list.Count,list.Count,"Done");}
 public async Task<(AudioAnalysis Basic,AdvancedAudioAnalysis Advanced,ReplayGain Gain)> AnalyzeAsync(Song song,CancellationToken ct=default)
 {
   var basic=await db.GetAnalysisAsync(song.Id);var adv=await db.GetAdvancedAnalysisAsync(song.Id);var rg=await db.GetReplayGainAsync(song.Id);if(basic is not null&&adv is not null&&rg is not null)return(basic,adv,rg);
   var samples=await DecodeMonoAsync(song.Path,11025,Math.Min(song.DurationMs/1000d,240),ct);if(samples.Length<2048)throw new InvalidOperationException("Audio analysis returned too few samples");
   var rms=Math.Sqrt(samples.Select(x=>(double)x*x).Average());var peak=samples.Max(x=>Math.Abs(x));float lufs=(float)(20*Math.Log10(Math.Max(rms,1e-9))-.691);float peakDb=(float)(20*Math.Log10(Math.Max(peak,1e-9)));var bpm=EstimateBpm(samples,11025,out var beatOffset,out var conf);float interval=bpm>0?60000f/bpm:0;var (key,camelot,keyConf)=EstimateKey(samples,11025);float energy=(float)Math.Clamp(rms*4,0,1);float centroid=SpectralCentroid(samples,11025);float dyn=(float)Math.Max(0,peakDb-lufs);float dance=Math.Clamp(conf*(bpm is >=85 and <=150?1f:.65f),0,1);float valence=Math.Clamp(.42f+((centroid-1800)/8000f)+((key.Contains('m'))?-.12f:.1f),0,1);string mood=energy>.72&&valence>.55?"energetic":energy<.3?"calm":valence<.4?"dark":"balanced";
   var beats=new List<long>();if(interval>0)for(double t=beatOffset;t<song.DurationMs&&beats.Count<10000;t+=interval)beats.Add((long)t);long now=DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();int gain=(int)Math.Clamp((-14-lufs)*100,-1800,1200);basic=new(song.Id,lufs,peakDb,bpm,gain,now);adv=new(song.Id,bpm,interval,beatOffset,conf,16,beatOffset,conf*.8f,key,camelot,keyConf,energy,valence,dance,centroid,dyn,mood,JsonSerializer.Serialize(beats),now);float gainDb=Math.Clamp(-14-lufs,-18,12);rg=ReadReplayGainTags(song)??new(song.Id,gainDb,null,peak,null,"analysis",now);await db.SaveAnalysisAsync(basic);await db.SaveAdvancedAnalysisAsync(adv);await db.SaveReplayGainAsync(rg);return(basic,adv,rg);
 }
 static ReplayGain? ReadReplayGainTags(Song s){try{using var f=TagLib.File.Create(s.Path);var tags=f.TagTypes==TagLib.TagTypes.None?null:f.GetTag(TagLib.TagTypes.Id3v2,false) as TagLib.Id3v2.Tag;if(tags is null)return null;float? Find(string key){var frame=tags.GetFrames<TagLib.Id3v2.UserTextInformationFrame>().FirstOrDefault(x=>x.Description.Equals(key,StringComparison.OrdinalIgnoreCase));if(frame?.Text.FirstOrDefault() is string v){v=v.Replace("dB","",StringComparison.OrdinalIgnoreCase).Trim();if(float.TryParse(v,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var g))return g;}return null;}var tg=Find("REPLAYGAIN_TRACK_GAIN");var ag=Find("REPLAYGAIN_ALBUM_GAIN");if(tg is null&&ag is null)return null;return new(s.Id,tg,ag,null,null,"tag",DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());}catch{return null;}}
 static async Task<float[]> DecodeMonoAsync(string path,int rate,double seconds,CancellationToken ct)
 {
  var psi=new ProcessStartInfo(FfmpegLocator.Require()){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};
  foreach(var arg in new[]{"-hide_banner","-loglevel","error","-i",path,"-t",seconds.ToString(System.Globalization.CultureInfo.InvariantCulture),"-vn","-ac","1","-ar",rate.ToString(System.Globalization.CultureInfo.InvariantCulture),"-f","f32le","pipe:1"})psi.ArgumentList.Add(arg);
  using var p=new Process{StartInfo=psi}; p.Start(); using var ms=new MemoryStream(); await p.StandardOutput.BaseStream.CopyToAsync(ms,ct); await p.WaitForExitAsync(ct);
  if(p.ExitCode!=0 && ms.Length==0)throw new InvalidOperationException("FFmpeg could not decode this track for analysis.");
  var bytes=ms.ToArray();var a=new float[bytes.Length/4];Buffer.BlockCopy(bytes,0,a,0,a.Length*4);return a;
 }
 static float EstimateBpm(float[] s,int sr,out float offsetMs,out float confidence){int hop=512,win=1024,n=Math.Max(1,(s.Length-win)/hop);var env=new float[n];double prev=0;for(int i=0;i<n;i++){double e=0;int start=i*hop;for(int j=0;j<win;j++){var x=s[start+j];e+=x*x;}e=Math.Sqrt(e/win);env[i]=(float)Math.Max(0,e-prev);prev=e;}var mean=env.Average();for(int i=0;i<env.Length;i++)env[i]=Math.Max(0,env[i]-mean*.65f);int minLag=(int)(60d/190*sr/hop),maxLag=(int)(60d/60*sr/hop);double best=0;int bestLag=minLag;for(int lag=minLag;lag<=maxLag;lag++){double c=0;for(int i=lag;i<env.Length;i++)c+=env[i]*env[i-lag];if(c>best){best=c;bestLag=lag;}}float bpm=(float)(60d*sr/(hop*bestLag));double norm=env.Sum(x=>x*x)+1e-9;confidence=(float)Math.Clamp(best/norm*3,0,1);int maxI=0;for(int i=1;i<Math.Min(bestLag,env.Length);i++)if(env[i]>env[maxI])maxI=i;offsetMs=(float)(maxI*hop*1000d/sr);return bpm;}
 static (string,string,float) EstimateKey(float[] s,int sr){var chroma=new double[12];int nfft=4096;int step=8192;var win=new float[nfft];for(int st=0;st+nfft<s.Length;st+=step){Array.Copy(s,st,win,0,nfft);var mag=FftMagnitude(win);for(int k=1;k<mag.Length;k++){double hz=k*sr/(double)nfft;if(hz<65||hz>4200)continue;double midi=69+12*Math.Log2(hz/440);int pc=((int)Math.Round(midi)%12+12)%12;chroma[pc]+=mag[k];}}var major=new[]{6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88};var minor=new[]{6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17};double best=-1,second=-1;int root=0;bool min=false;for(int r=0;r<12;r++)foreach(var mm in new[]{false,true}){var prof=mm?minor:major;double score=0;for(int i=0;i<12;i++)score+=chroma[(i+r)%12]*prof[i];if(score>best){second=best;best=score;root=r;min=mm;}else if(score>second)second=score;}string[] names={"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"};string key=names[root]+(min?"m":"");string camel=Camelot(root,min);float conf=(float)Math.Clamp((best-second)/(Math.Abs(best)+1e-9)*8,0,1);return(key,camel,conf);}
 static string Camelot(int root,bool minor){string[] maj={"8B","3B","10B","5B","12B","7B","2B","9B","4B","11B","6B","1B"};string[] min={"5A","12A","7A","2A","9A","4A","11A","6A","1A","8A","3A","10A"};return(minor?min:maj)[root];}
 static float SpectralCentroid(float[] s,int sr){int n=4096;var x=s.Take(n).Concat(Enumerable.Repeat(0f,n)).Take(n).ToArray();var m=FftMagnitude(x);double num=0,den=0;for(int i=1;i<m.Length;i++){double hz=i*sr/(double)n;num+=hz*m[i];den+=m[i];}return(float)(num/(den+1e-9));}
 static double[] FftMagnitude(float[] input){int n=1;while(n<input.Length)n<<=1;var re=new double[n];var im=new double[n];for(int i=0;i<input.Length;i++)re[i]=input[i]*(.5-.5*Math.Cos(2*Math.PI*i/Math.Max(1,input.Length-1)));for(int j=1,i=0;j<n;j++){int bit=n>>1;for(;i>=bit;bit>>=1)i-=bit;i+=bit;if(j<i)(re[j],re[i])=(re[i],re[j]);}for(int len=2;len<=n;len<<=1){double ang=-2*Math.PI/len;for(int i=0;i<n;i+=len){for(int j=0;j<len/2;j++){double wr=Math.Cos(ang*j),wi=Math.Sin(ang*j);double ur=re[i+j],ui=im[i+j];double vr=re[i+j+len/2]*wr-im[i+j+len/2]*wi;double vi=re[i+j+len/2]*wi+im[i+j+len/2]*wr;re[i+j]=ur+vr;im[i+j]=ui+vi;re[i+j+len/2]=ur-vr;im[i+j+len/2]=ui-vi;}}}var mag=new double[n/2];for(int i=0;i<mag.Length;i++)mag[i]=Math.Sqrt(re[i]*re[i]+im[i]*im[i]);return mag;}
}